language: java

branches:
  only:
    - master

env:
  global:
    - EXPO_SDK_VERSION="39.0.0"
    - TURTLE_VERSION="0.18.8"
    - NODE_VERSION="12.13.1"
    - YARN_VERSION="1.21.1"

jobs:
  include:
    - stage: publish app
      env:
        - CACHE_NAME=publish YARN_CACHE_FOLDER="/home/travis/yarn_cache"
      cache:
        directories:
          - $HOME/yarn_cache
      before_install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn global add expo-cli
      script:
        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
        - yarn
        - expo publish

